# YAML for setting up a conda environment
name: wetter
channels:
#  - conda-forge
  - defaults
dependencies:
  - jupyter
  - matplotlib
  - numpy
  - pandas
  - seaborn
  - python=3.13
  - seaborn
  - plotly
